os: linux
group: stable
dist: trusty
language: generic

env:
  - DOCKER_SHELL=bash:4
  - DOCKER_SHELL=bash:5
  - DOCKER_SHELL=zshusers/zsh:5.6

before_install:
  - bash <(curl -sL https://git.io/get-docker-compose)
  - make travis-pull

script:
  - make travis-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
