os: linux
group: stable
dist: trusty
language: generic

env:
  - SHELL=bash:4
  - SHELL=bash:5

before_install:
  - bash <(curl -sL https://git.io/get-docker-compose)

script:
  - make test-travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
